### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by andreaslutsch** [creecros/Group_assign#60]
Updated kanboard to php 8 and using this plugin it seems when going to see a project, php fails:

```
2021/04/01 12:27:00 [error] 121539#121539: *102 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Unknown named parameter $project in /var/www/***/app/Helper/HookHelper.php:51
Stack trace:
#0 /var/www/dev.esforces.com/app/Helper/HookHelper.php(51): call_user_func_array()
#1 /var/www/dev.esforces.com/app/Template/app/filters_helper.php(21): Kanboard\Helper\HookHelper->render()
#2 /var/www/dev.esforces.com/app/Core/Template.php(83): include('...')
#3 /var/www/dev.esforces.com/app/Template/project_header/search.php(11): Kanboard\Core\Template->render()
#4 /var/www/dev.esforces.com/app/Core/Template.php(83): include('...')
#5 /var/www/dev.esforces.com/app/Template/project_header/header.php(12): Kanboard\Core\Template->render()
#6 /var/www/dev.esforces.com/app/Core/Template.php(83): include('...')
#7 /var/www/dev.esforces.com/app/Helper/ProjectHeaderHelper.php(56): Kanboard\Core\Template->render()
#8 /var/www/dev.esforces.com/app/Template/board/view_private.php(3): Kanboard\Helper\ProjectHeaderHelper->render()
#9 /var/www/dev.esforces.com/" while reading response header from upstream, client: ***, server: ***, request: "GET /?controller=BoardViewController&action=show&project_id=3&search=status%3Aopen HTTP/1.0", upstream: "fastcgi://unix:/run/php/php8.sock:", host: "***", referrer: "https://***/board/3"
```

**Comment by creecros** [comment]
until I get a chance to figure out what's changed in php 8, since I haven't really been keeping up, ill just have to say it's not compatible with php 8 at the moment.

**Comment by creecros** [comment]
@andreaslutsch 

I have at least narrowed it down to the dropdown filter added here: https://github.com/creecros/Group_assign/commit/e47eba433edb3cacc6d1a9f92d8a36483268d469#diff-e8b8b3aeed1bb6d828a1068cb8b8ab0aedf1d493f49be9684e2a2f679a58ceaa

by @BlueTeck . I truly do not understand what the issue is, but it appears that before php8, keys that weren't expected were ignored, and now they do not get ignored, but if you remove the hook, or just comment it out for now, it will at least allow you to use the plugin with php8.
```

**Comment by Chaosmeister** [comment]
#64 fixes the behaviour while keeping the hook active

**Comment by creecros** [comment]
you rock
